export let tasks = [
    {
        "id": 23,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et  cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': false,
    },
    {
        "id": 24,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': true,
    },
    {
        "id": 25,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': true,
    },
    {
        "id": 26,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': 'in-progress',
    },
    {
        "id": 27,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': true,
    },
    {
        "id": 28,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': false,
    },
    {
        "id": 29,
        'title': 'Переписать проект на Vue 3',
        'description': 'Quia et suscipitnsuscipit recusandae consequuntur expedita et cumnreprehenderit molestiae ut ut quas totamnnostrum rerum est autem sunt rem eveniet architecto',
        'date': '21.10.21',
        'time': '14:31',
        'status': 'in-progress',
    },
];